=== 15831944/hello-world/trunk/bin/report/lingliaobiao.xsd
<?xml version="1.0" encoding="GB2312" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.techtimesun.com" xmlns="http://www.techtimesun.com" elementFormDefault="unqualified">
    <xs:element name="data">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="info_0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:all>
                            <xs:element name="CompanyLogoUrl" type="xs:string" minOccurs="0" />
                            <xs:element name="CompanyName" type="xs:string" minOccurs="0" />
                            <xs:element name="OrderCodeUrl" type="xs:string" minOccurs="0" />
                            <xs:element name="OrderID" type="xs:string" minOccurs="0" />
                            <xs:element name="ShiftEmployee" type="xs:string" minOccurs="0" />
                            <xs:element name="ShiftDate" type="xs:string" minOccurs="0" />
                            <xs:element name="UseEmployee" type="xs:string" minOccurs="0" />
                            <xs:element name="UseDate" type="xs:string" minOccurs="0" />
                            <xs:element name="ManageEmployee" type="xs:string" minOccurs="0" />
                            <xs:element name="OrderStore" type="xs:string" minOccurs="0" />
                            <xs:element name="AuditEmployee" type="xs:string" minOccurs="0" />
                            <xs:element name="UseMachineName" type="xs:string" minOccurs="0" />
                            <xs:element name="OrderMoreInfo" type="xs:string" minOccurs="0" />
                        </xs:all>
                    </xs:complexType>
                </xs:element>
                <xs:element name="info_1" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:all>
                            <xs:element name="Index" type="xs:string" minOccurs="0" />
                            <xs:element name="Thickness" type="xs:string" minOccurs="0" />
                            <xs:element name="WidthHeight" type="xs:string" minOccurs="0" />
                            <xs:element name="Code" type="xs:string" minOccurs="0" />
                            <xs:element name="PanelMatrial" type="xs:string" minOccurs="0" />
                            <xs:element name="PanelNum" type="xs:string" minOccurs="0" />
                            <xs:element name="Units" type="xs:string" minOccurs="0" />
                            <xs:element name="Brand" type="xs:string" minOccurs="0" />
                            <xs:element name="Remark" type="xs:string" minOccurs="0" />
                        </xs:all>
                    </xs:complexType>
                </xs:element>
                <xs:element name="info_2" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:all>
                            <xs:element name="PanelMatrial" type="xs:string" minOccurs="0" />
                            <xs:element name="Thickness" type="xs:string" minOccurs="0" />
                            <xs:element name="SmallPanelNum" type="xs:string" minOccurs="0" />
                            <xs:element name="TotalArea" type="xs:string" minOccurs="0" />
                        </xs:all>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== 15831944/hello-world/trunk/bin/report/lingliaobiao.xml
<?xml version="1.0" encoding="GB2312" ?>
<data xmlns="http://www.techtimesun.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.techtimesun.com lingliaobiao.xsd">
    <info_0>
        <CompanyLogoUrl>..\ico\logo.jpg</CompanyLogoUrl>
        <CompanyName>22222222222</CompanyName>
        <OrderCodeUrl>333333333</OrderCodeUrl>
        <OrderID>4444444444</OrderID>
        <ShiftEmployee>55555555</ShiftEmployee>
        <ShiftDate>666666666</ShiftDate>
        <UseEmployee>77777777</UseEmployee>
        <UseDate>888888888</UseDate>
        <ManageEmployee>99999999</ManageEmployee>
        <OrderStore>AAAAAAAAA</OrderStore>
        <AuditEmployee>BBBBBBBBBB</AuditEmployee>
        <UseMachineName>CCCCCCCC</UseMachineName>
        <OrderMoreInfo>DDDDDDDD</OrderMoreInfo>
    </info_0>
    <info_1>
        <Index>1</Index>
        <Thickness>18.0</Thickness>
        <WidthHeight>2440.0 x 1220.0</WidthHeight>
        <Code></Code>
        <PanelMatrial>рзн╛яе/3030╣Чс╟оПд╬ E0</PanelMatrial>
        <PanelNum>28</PanelNum>
        <Units>©И</Units>
        <Brand></Brand>
        <Remark></Remark>
    </info_1>
    <info_1>
        <Index>2</Index>
        <Thickness>9.0</Thickness>
        <WidthHeight>2440.0 x 1220.0</WidthHeight>
        <Code></Code>
        <PanelMatrial>рзн╛яе/3030╣Чс╟оПд╬ E0</PanelMatrial>
        <PanelNum>10</PanelNum>
        <Units>©И</Units>
        <Brand></Brand>
        <Remark></Remark>
    </info_1>
    <info_1>
        <Index>3</Index>
        <Thickness>20.0</Thickness>
        <WidthHeight>2440.0 x 1220.0</WidthHeight>
        <Code></Code>
        <PanelMatrial>рзн╛яе/5001╧╛м╒╨клрд╬ E0</PanelMatrial>
        <PanelNum>1</PanelNum>
        <Units>©И</Units>
        <Brand></Brand>
        <Remark></Remark>
    </info_1>
    <info_1>
        <Index>4</Index>
        <Thickness>18.0</Thickness>
        <WidthHeight>2440.0 x 1220.0</WidthHeight>
        <Code></Code>
        <PanelMatrial>рзн╛яе/5001╧╛м╒╨клрд╬ E0</PanelMatrial>
        <PanelNum>1</PanelNum>
        <Units>©И</Units>
        <Brand></Brand>
        <Remark></Remark>
    </info_1>
    <info_2>
        <PanelMatrial>рзн╛яе/3030╣Чс╟оПд╬ E0</PanelMatrial>
        <Thickness>18.0</Thickness>
        <SmallPanelNum>155</SmallPanelNum>
        <TotalArea>72.821</TotalArea>
    </info_2>
    <info_2>
        <PanelMatrial>рзн╛яе/3030╣Чс╟оПд╬ E0</PanelMatrial>
        <Thickness>9.0</Thickness>
        <SmallPanelNum>12</SmallPanelNum>
        <TotalArea>18.482</TotalArea>
    </info_2>
    <info_2>
        <PanelMatrial>рзн╛яе/5001╧╛м╒╨клрд╬ E0</PanelMatrial>
        <Thickness>20.0</Thickness>
        <SmallPanelNum>2</SmallPanelNum>
        <TotalArea>0.668</TotalArea>
    </info_2>
    <info_2>
        <PanelMatrial>рзн╛яе/5001╧╛м╒╨клрд╬ E0</PanelMatrial>
        <Thickness>18.0</Thickness>
        <SmallPanelNum>4</SmallPanelNum>
        <TotalArea>1.714</TotalArea>
    </info_2>
</data>
